# Generated by Django 4.0.1 on 2022-01-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('same_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('to_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flag', models.CharField(blank=True, max_length=10, null=True)),
                ('visa_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('covid_status', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_feedback_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
