# Generated by Django 4.0.1 on 2022-01-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=30)),
                ("brand", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("here", "В наличии"),
                            ("sold", "Продано"),
                            ("not_available", "Недоступна"),
                        ],
                        default="here",
                        max_length=13,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
